package org.app.Report;


import com.itextpdf.text.*;
import com.itextpdf.text.pdf.PdfWriter;
import lombok.AllArgsConstructor;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Date;

@AllArgsConstructor
public class SalesReport extends AbstractReport {
    private final static String fileName = "SalesReport.pdf";
    public void writeReport()
            throws DocumentException, IOException {
            Document salesReport = new Document();
            createDirectory(DIR);
            String FILE = DIR + fileName;
            Path pathFile = Paths.get(FILE);
            PdfWriter.getInstance(salesReport, Files.newOutputStream(pathFile));
            salesReport.open();
            addMetaData(salesReport);
            addTitlePage(salesReport);
            for (int i = 1; i <= 10; i++){
                addBill(salesReport,i);
            }
            salesReport.close();
    }

    private static void addMetaData(Document document) {
        document.addTitle("BMNO Report");
        document.addSubject("Sales Report");
        document.addKeywords("Java, PDF, iText, Tubes");
        document.addAuthor("COC");
        document.addCreator("COC");
    }

    private static void addTitlePage(Document document)
            throws DocumentException {
        Paragraph preface = new Paragraph();
        preface.add(new Paragraph("Sales Report", titleFont));
        addEmptyLine(preface, 1);
        preface.add(new Paragraph(
                "Report generated by: " + System.getProperty("user.name") + ", " + new Date(), //$NON-NLS-1$ //$NON-NLS-2$ //$NON-NLS-3$
                normalBold));
        addEmptyLine(preface, 3);
        preface.add(new Paragraph(
                "This document describes all sales report from BNMO application",
                bigFont));
        document.add(preface);
        document.newPage();
    }
    private static void addBill(Document document, int idx) throws DocumentException {
        String customerNumber = "Bill Customer " + String.valueOf(idx);
        Anchor anchor = new Anchor(customerNumber, titleFont);
        anchor.setName(customerNumber);

        Chapter currentChapter = new Chapter(new Paragraph(anchor), idx);

        Paragraph subPara = new Paragraph("Item 1", subFont);
        Section subCatPart = currentChapter.addSection(subPara);
        createList(subCatPart);

        document.add(currentChapter);
    }
    private static void createList(Section section) {
        List list = new List(true, false, 10);
        list.add(new ListItem("Quantity "));
        list.add(new ListItem("Order types "));
        list.add(new ListItem("Notes "));
        section.add(list);
    }

}
